allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

allprojects { p ->
    def newBuildDir = rootProject.layout.buildDirectory.dir("../../build").get()
    p.layout.buildDirectory.value(newBuildDir.dir(p.name))
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete(rootProject.layout.buildDirectory)
}
